---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Страница регистрации с формой ввода логина, пароля, e-mail и телефона для связи с клиентом для обработки последующего заказа
  - Страница входа. Доступ к личному кабинету. Приложение должно запоминать, что пользователь авторизован
  - При изменении языка с английского на русский переводится весь сайт (корректно работает поиск на русском, описание товара на русском, перевод категорий на русский, цены товаров на сайте указаны в рублях, в корзине сумма заказа указана в рублях)
  - При добавлении пользователем товара в корзину должна быть возможность сразу указать желаемое количество товара для заказа
  - У пользователя должна быть возможность менять количество товара в корзине
  - В поле "Цена" нельзя внести отрицательное значение
  - Пользователь не должен иметь доступ к чужим корзинам
